repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: clang-format
        files: ^(src|hw)/
        exclude: 'lib/|idf_component.yml'
    -   id: cpplint
        files: ^(src|hw)/
        exclude: 'lib/|idf_component.yml'
        args: ['--filter=-build/include_order,-runtime/references']
    -   id: cppcheck
        args: [--force,--check-level=exhaustive,--suppress=syntaxError]
        files: ^(src|hw)/
        exclude: 'lib/|idf_component.yml'
